### ISSUE TITLE
Guitar Praise controller

### ISSUE THREAD

**Issue by BenMcLean** [TheNathannator/PlasticBand#10]
[Guitar Priase](https://en.wikipedia.org/wiki/Guitar_Praise) is a very low quality piece of software, but it came bundled with a surprisingly high quality USB hardware peripheral. I know I've still got it in my closet. Could perhaps get documented here?

**Comment by TheNathannator** [comment]
Already is! [Overview](https://github.com/TheNathannator/PlasticBand/blob/main/Docs/Instruments/5-Fret%20Guitar/Guitar%20Praise%20Guitar.md), [HID descriptor](https://github.com/TheNathannator/PlasticBand/blob/main/Docs/Descriptor%20Dumps/HID/Guitar%20Praise%20HID%20Descriptor.txt), [USB descriptor](https://github.com/TheNathannator/PlasticBand/blob/main/Docs/Descriptor%20Dumps/HID/Guitar%20Praise%20USB%20Descriptor.txt)

If you have anything to add though, that would be fantastic!

**Comment by BenMcLean** [comment]
Sorry,  missed it. :)
